### ISSUE TITLE
bad project

### ISSUE THREAD

**Issue by SeekPoint** [zqhZY/semanaly#3]

**Comment by zqhZY** [comment]
嗯嗯，大佬您说的是

**Comment by zqhZY** [comment]
Spray everywhere，Github is no exception, sad.

**Comment by SeekPoint** [comment]
how do you get so many start for this XX

**Comment by zqhZY** [comment]
一、中国人口基数大，60+我觉得不算多；
二、如果说这个垃圾项目的star您觉得多，可能是因为博客的引流，另外只要有一点帮助，有人可能就会star，另外我刚看了一下star列表，可能小白占一半吧，
三、这个仓库不是严谨的项目，是自己之前用过的一些demo脚本，没有组织结构，甚至目录之间没有联系，跟你讲的一样乱的跟一坨屎一样；
四、垃圾项目也可以发布，自己云笔记也ok，本身就是一个被访问的页面，没有什么造福所有人的义务。
五、您戾气太重，如果你一开始就用“bad project”做issue标题，我也不会回复
六、没什么建设性意见，等会就close了，

**Comment by SeekPoint** [comment]
thanks
